#
# Makefile.mingw
#
# Description: Makefile for win32 (mingw) version of meanwhile
#


##
## INCLUDE  MAKEFILES
##

#My Gaim src directory is just "GAIM" not GAIM0v.79 or whatever.  Change to match yours -jknight
include ../gaim/src/win32/global.mak



all:
	make -C src all


install:
	make -C src install


clean:
	make -C src clean
