#! /bin/sh

# Test script for Python wrappers
#
# If you don't have a test.conf, copy it from test.conf.in and modify
# as necessary.

# obtain configuration data
. test.conf

cd src/python

export LD_LIBRARY_PATH=$py_lib:../.libs/

if test "$1" = "debug" ; then
	gdb --args $py_bin -v test.py
else
	$py_bin test.py 
fi

